-- Migration 014 — cron run history
--
-- Adds a lightweight audit table so the dashboard can show "last cron
-- run: OK · 2 invoices, 1 reminder, 0 errors" without scraping Railway
-- logs. Written to from `daily_invoicing.py` after Migration 014 is
-- applied; until then the daily-invoicing endpoint continues to function
-- exactly as before — the audit write is best-effort and never blocks
-- the actual invoicing work.
--
-- Design:
--   * ONE row per cron invocation, keyed by autogenerated id.
--   * `job_name` is a free string so future cron jobs (deliverable
--     expiry sweep, retainer renewal, etc.) can share the same table.
--   * `started_at` set on insert; `finished_at` filled by an UPDATE at
--     the end. If a run crashes hard mid-way, finished_at stays NULL —
--     that's a meaningful "died mid-run" signal.
--   * `summary` is the full JSON body the endpoint returns. Storing it
--     verbatim means the dashboard can render any counters we add later
--     without a migration; new fields just appear.
--   * `error_count` denormalised from summary.errors[] for cheap
--     ordering / filtering.
--   * `ok` = (error_count == 0 AND finished_at IS NOT NULL). Also
--     denormalised — a partial index on `ok=false` gives the dashboard
--     a fast "any bad runs recently?" scan.
--
-- RLS: no anon/authenticated policies. Only service-role (admin backend
-- routes) can read/write. Cron-token routes execute under service role.

begin;

create table if not exists public.cron_runs (
    id            uuid primary key default gen_random_uuid(),
    job_name      text not null,
    started_at    timestamptz not null default now(),
    finished_at   timestamptz,
    summary       jsonb not null default '{}'::jsonb,
    error_count   int  not null default 0 check (error_count >= 0),
    ok            boolean not null default true
);

comment on table public.cron_runs is
  'Audit trail for scheduled jobs (Migration 014). One row per invocation. '
  'summary stores the endpoint response body verbatim.';

-- Fast "most recent runs for job X" queries.
create index if not exists cron_runs_job_started_idx
  on public.cron_runs (job_name, started_at desc);

-- Partial index for "any failing runs?" — tiny, fast, only indexes rows
-- that are actually bad.
create index if not exists cron_runs_bad_idx
  on public.cron_runs (started_at desc)
  where ok = false;

alter table public.cron_runs enable row level security;
-- No policies created. Only service-role bypass. Same convention as
-- other admin-only tables in this project.

commit;
